### PR TITLE
feat: upsert search attributes

### PR DESCRIPTION
**Pull request by cv65kr**
image

# Reason for This PR

https://github.com/temporalio/sdk-php/issues/76

Same functionality like in GO-SDK - https://github.com/temporalio/samples-go/tree/main/searchattributes

Dependecy: https://github.com/temporalio/roadrunner-temporal/pull/275

## Checklist

1. Closes
https://github.com/temporalio/sdk-php/issues/76

2. How was this tested:
Integration tests

### CODE REVIEW

**Comment by seregazhuk** [comment]
@cv65kr Thank you for your request! Have your tried to run your test localy? It hangs on this line:
```php
$this->assertSame('done', $workflow->getResult());
```

**Comment by seregazhuk** [comment]
I have tried it on both real and test servers. In both cases RR failes with the following error:
```
Workflow panic  {"Namespace": "default", "TaskQueue": "default", "WorkerID": "default:7d24e567-e217-4a80-9151-8820ca788c9b", "WorkflowType": "UpsertSearchAttributesWorkflow", "WorkflowID": "b346e54f-9652-4c7c-beca-94ef41faacd8", "RunID": "f8c6b3f1-665a-4b1f-892c-c6c97d71cfd4", "Attempt": 9, "Error": "runtime error: invalid memory address or nil pointer dereference", "StackTrace": "process event for default [panic]:\ngithub.com/temporalio/roadrunner-temporal/internal/codec/proto.(*Codec).Decode(0x14000b0d5c0, 0x140001299c0, 0x1400066d200)\n\tgithub.com/temporalio/roadrunner-temporal@v1.6.2/internal/codec/proto/proto.go:92 +0x1d0\ngithub.com/temporalio/roadrunner-temporal/aggregatedpool.(*Workflow).flushQueue(0x14000b40c30)\n\tgithub.com/temporalio/roadrunner-temporal@v1.6.2/aggregatedpool/handler.go:333 +0x2b0\ngithub.com/temporalio/roadrunner-temporal/aggregatedpool.(*Workflow).OnWorkflowTaskStarted(0x14000b40c30, 0x1400081c5a0?)\n\tgithub.com/temporalio/roadrunner-temporal@v1.6.2/aggregatedpool/workflow.go:151 +0x18c\ngo.temporal.io/sdk/internal.(*workflowExecutionEventHandlerImpl).ProcessEvent(0x14000139c80, 0x14000129640, 0xe0?, 0x1)\n\tgo.temporal.io/sdk@v1.17.0/internal/internal_event_handlers.go:894 +0x1ac\ngo.temporal.io/sdk/internal.(*workflowExecutionContextImpl).ProcessWorkflowTask(0x14000244680, 0x14000237d10)\n\tgo.temporal.io/sdk@v1.17.0/internal/internal_task_handlers.go:904 +0xa58\ngo.temporal.io/sdk/internal.(*workflowTaskHandlerImpl).ProcessWorkflowTask(0x14000ada2c0, 0x14000237d10, 0x14000750180)\n\tgo.temporal.io/sdk@v1.17.0/internal/internal_task_handlers.go:751 +0x32c\ngo.temporal.io/sdk/internal.(*workflowTaskPoller).processWorkflowTask(0x14000b27c70, 0x14000237d10)\n\tgo.temporal.io/sdk@v1.17.0/internal/internal_task_pollers.go:290 +0x2d0\ngo.temporal.io/sdk/internal.(*workflowTaskPoller).ProcessTask(0x14000b27c70, {0x10470e1c0?, 0x14000237d10?})\n\tgo.temporal.io/sdk@v1.17.0/internal/internal_task_pollers.go:261 +0xb0\ngo.temporal.io/sdk/internal.(*baseWorker).processTask(0x1400017a640, {0x10470dd80, 0x14000207f80})\n\tgo.temporal.io/sdk@v1.17.0/internal/internal_worker_base.go:426 +0x158\ncreated by go.temporal.io/sdk/internal.(*baseWorker).runTaskDispatcher\n\tgo.temporal.io/sdk@v1.17.0/internal/internal_worker_base.go:324 +0x98"}
```

Ping @rustatian here 🌚

**Comment by cv65kr** [comment]
@seregazhuk yes, I tested it locally and everything working fine.

The problem is that you are trying use Road runner version without my changes - https://github.com/temporalio/roadrunner-temporal/pull/275 They are not released yet, so you need to compile it by it own.

Or try run my branch from E2E https://github.com/roadrunner-server/rr-e2e-tests/pull/138 (Same test is copied there)

**Comment by rustatian** [comment]
released in `v2.11.4-beta.1`

**Pull request merged**
