### PR TITLE
[Critical bug] fix: default `Activity`'s `taskQueue`

### PR DESCRIPTION
**Pull request by ruscon**
## What was changed

Change the default value of `Activity`'s `taskQueue` from `default` to `null`.

## Why?

It allows automatically propagating` Workflow`'s queue to the `Activity` queue name by default, as described in [the documentation](https://docs.temporal.io/application-development/foundations#set-task-queue)

## Checklist

1. Closes 

2. How was this tested:

Tested locally.

3. Any docs updates needed?

Nope.

### CODE REVIEW

**Comment by roxblnfk** [comment]
It can be breaking change.
@wolfy-j wdyt?

**Comment by ruscon** [comment]
Tests have been fixed and the code has been rebased.

Locally I have a bug(?) with the tests
```bash
Error: Class "Grpc\ChannelCredentials" not found
```

Probably it will be ok in CI


@roxblnfk 
>It can be breaking change.
It could.

**Comment by ruscon** [comment]
@roxblnfk Some tests failed, but they probably just need to be re-run.

**Comment by roxblnfk** [comment]
> @roxblnfk Some tests failed, but they probably just need to be re-run (I see the same problem in other PRs)

Yea. Don't worry about it

**Comment by roxblnfk** [comment]
Hi @ruscon. Could you sing CLA again?

**Comment by ruscon** [comment]
@roxblnfk 
> license/cla — Contributor License Agreement is signed.

**Review by roxblnfk — APPROVED** [review]

**Comment by roxblnfk** [comment]
Ok. Thank you!

**Comment by ruscon** [comment]
@roxblnfk Could you tag it, please?

**Comment by roxblnfk** [comment]
> @roxblnfk Could you tag it, please?

Certainly!

**Pull request merged**
