### PR TITLE
Add support for custom reader in WorkerFactory.

### PR DESCRIPTION
**Pull request by Zylius**
## What was changed

Introduced an ability to extend worker factory.

Dunno if I should make other `create*()` methods protected as well, besides reader.

## Why?

So a custom reader could be used. To be able to read activty/workflow config not only from annotations, but preset arrays etc.

## Checklist

1. Closes https://github.com/temporalio/sdk-php/issues/110

2. How was this tested: Unit tests.

3. Any docs updates needed? No. Its self explanatory and no BC.

### CODE REVIEW

**Comment by Zylius** [comment]
Related comment: https://github.com/temporalio/sdk-php/pull/115#issuecomment-874200948

**Comment by Zylius** [comment]
Hello, is this still in consideration? This issue is kinda blocking our work with temporal so I was thinking if we should just use our own fork of the sdk.

**Review by SerafimArts — APPROVED** [review]
Of all the possible options, I think this is the simplest. 

Moreover, when we add a container, such an implementation may not even break anything... Probably... :)

**Review by wolfy-j — APPROVED** [review]

**Comment by Zylius** [comment]
Thank you guys! :bow:

**Pull request merged**
