### PR TITLE
Allow for higher versions of Carbon

### PR DESCRIPTION
**Pull request by hotmeteor**
## What was changed

Unlocked `nesbot/carbon` from `2.52.*` to `^2.52.0`

## Why?

Temporal was incompatible to latest versions of Laravel when Carbon is locked to `2.52.*`

Tested against latest Laravel version (8.81.0)

### CODE REVIEW

**Comment by seregazhuk** [comment]
@hotmeteor Thank you for your request 👍 Looks like some tests are failing. Can you check them please?

**Comment by hotmeteor** [comment]
Is there something special I need to do to get tests to run locally? I keep seeing this error pop up in multiple tests, ie:
```sh
42) Temporal\Tests\Functional\Client\UntypedWorkflowStubTestCase::testTerminated
Error: Class "Grpc\ChannelCredentials" not found

/Users/adam/Web/sdk-php/src/Client/GRPC/BaseClient.php:57
/Users/adam/Web/sdk-php/tests/Functional/Client/ClientTestCase.php:34
/Users/adam/Web/sdk-php/tests/Functional/Client/UntypedWorkflowStubTestCase.php:185
```

**Comment by wolfy-j** [comment]
Hi, you have to install php-grpc extension via PECL.

**Comment by hotmeteor** [comment]
I ran it on PHP 7.4 locally and it passed, but I've made an additional change based on what I've seen elsewhere online. Let's see if this fixes it?

**Comment by eveclo-jackprice** [comment]
Would love to see this merged. Is there anything blocking that I could help with?

**Comment by wolfy-j** [comment]
Just restarted the tests. Let's see.

**Comment by seregazhuk** [comment]
@hotmeteor @eveclo-jackprice merged, thank you 👍

**Pull request merged**
