### PR TITLE
Issue 211. Test for readonly properties

### PR DESCRIPTION
**Pull request by shanginn**
Ok, I remember that readonly didn't work for me, but now they are working, so I created a test case for it. In order for it to work we need to add php 8.1 in CI matrix settings.

But php 8.1 will not work with current lower versions.

The questions is - do you want to add php 8.1 support? If no, I can just add the test and it will be waiting for the version upgrade.

There is another question: how should I go about testing this behavior: with **marshaller** or with **payload converter**? I created both, but I think that one of them is enough. Or both is good?

## What was changed
Added test that covers [readonly properties issue](https://github.com/temporalio/sdk-php/issues/211)

## Why?
Because issue is open and I though readonly properties would not work, but surprisingly they are working just fine

## Checklist

1. Closes [issue 221](https://github.com/temporalio/sdk-php/issues/211)

2. How was this tested:
With unit test

### CODE REVIEW

**Comment by seregazhuk** [comment]
@shanginn have you tried functional tests with your changes? It fails, I think there are errors when running worker under RR.
https://github.com/temporalio/sdk-php/runs/7752350196?check_suite_focus=true

**Comment by shanginn** [comment]
I did check it under my branch, and it [went fine](https://github.com/shanginn/sdk-php/runs/7747314773?check_suite_focus=true)

**Comment by shanginn** [comment]
I rebased (or do you prefer merge?) this branch to the current master. in my fork [all the test are good](https://github.com/shanginn/sdk-php/actions/runs/2836983394)

**Comment by shanginn** [comment]
😢

**Review by seregazhuk — APPROVED** [review]
Thank you! 🔥

**Pull request merged**
